import type { Metadata } from "next";
import ClientLayout from "./client-layout";


export const metadata: Metadata = {
  title: "AMOHA | Adishakti Museum of Heritage & Arts",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>

      <ClientLayout>{children}</ClientLayout>
    </>
  );
}
